---
- name: Check for existing Hadoop installation
  stat: path="{{ hadoop_install_path }}"
  register: hadoop_dir
  tags:
    - provision

- name: Download Hadoop
  get_url: url='{{ hadoop_binaries_url }}' dest='{{ hadoop_download_path }}' mode=0755 validate_certs=no timeout=300
  when: not (hadoop_dir.stat.exists)
  tags:
    - provision

- name: Unarchive Hadoop in install folder
  unarchive: creates="{{ hadoop_install_path }}" copy=no src="{{ hadoop_download_path }}" dest="{{ install_base_path }}" owner=root group={{ hadoop_group }} mode=0755
  tags:
    - provision

- name: Create directories
  file: path={{ item.path }} state=directory owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
          - { path: "{{ hadoop_conf_dir }}", owner: 'root', group: '{{hadoop_group}}', mode: '0755' }
          - { path: "{{ yarn_nm_dir }}", owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0755' }
          - { path: "{{ hdfs_namenode_data_dir }}", owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0755' }
          - { path: "{{ hdfs_datanode_data_dir }}", owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0755' }
          - { path: "{{ hadoop_log_dir }}", owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0777' }
          - { path: "{{ hadoop_tmp_dir }}", owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0777' }
  tags:
    - configure

- name: Copy configuration scripts
  template: src={{ item.src }} dest="{{ hadoop_conf_dir }}" owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
          - { src: 'container-executor.cfg', owner: 'root', group: '{{hadoop_group}}', mode: '0440' }
          - { src: 'capacity-scheduler.xml', owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0444' }
          - { src: 'core-site.xml', owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0444' }
          - { src: 'yarn-site.xml', owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0444'  }
          - { src: 'mapred-site.xml', owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0444'  }
          - { src: 'hdfs-site.xml', owner: '{{hadoop_user}}', group: '{{hadoop_group}}', mode: '0444'  }
  tags:
    - configure

- name: Copy environment script
  template: src="env.sh.j2" dest="{{ hadoop_install_path }}/env.sh" owner={{ hadoop_user }} group={{ hadoop_group }} mode=0444
  tags:
    - configure

- name: Create symbolic link to Hadoop install directory
  file: src={{ hadoop_install_path }} path={{ hadoop_home }} state=link owner={{ hadoop_user }} group={{ hadoop_group }}
  tags:
    - configure

- name: Fix permissions on container executor binary
  file: path={{ container_executor_path }} owner=root group={{ hadoop_group }} mode=6050
  tags:
    - configure
